version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./dashboard:/app