version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5002:5002"
    networks:
      - dashboard-network
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

  frontend:
    build:
      context: ./dashboard
      dockerfile: Dockerfile

    ports:
      - "80:80"
    networks:
      - dashboard-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  dashboard-network:
    driver: bridge